# Generated by Django 4.0 on 2022-02-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='Products/', verbose_name='Card Image')),
            ],
        ),
        migrations.CreateModel(
            name='Imagini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Card', to='magazin.imagine')),
                ('images', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imagini', to='magazin.imagine')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret', models.FloatField(default=0, verbose_name='Pret')),
                ('reducere', models.IntegerField(default=0, verbose_name='Reducere')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, verbose_name='Stele')),
                ('count', models.IntegerField(default=0, verbose_name='Nr de feedback-uri')),
                ('accesari', models.BigIntegerField(default=0, verbose_name='Numar de accesari')),
            ],
        ),
        migrations.CreateModel(
            name='Specificatii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marime', models.CharField(default='XL', max_length=10, verbose_name='Mărime')),
                ('spalaremasina', models.BooleanField(default=True, verbose_name='Se spală la mașină')),
                ('temperatura', models.IntegerField(default=60, verbose_name='Temperatura de spălare recomandată')),
                ('timpspalare', models.CharField(default='2h', max_length=10, verbose_name='Timpul de spălare recomandat')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nume', models.CharField(max_length=50, verbose_name='Denumire')),
                ('descriere', models.TextField(blank=True, verbose_name='Descriere')),
                ('stoc', models.IntegerField(default=1, verbose_name='Stoc')),
                ('imagini', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imagini', to='magazin.imagini')),
                ('pret', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pret', to='magazin.pret')),
                ('rating', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rating', to='magazin.rating')),
                ('specificatii', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specificatii', to='magazin.specificatii')),
            ],
        ),
    ]
