# Generated by Django 4.0 on 2022-02-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_specificatii_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificatii',
            name='gen',
            field=models.TextField(choices=[('BARBATI', 'BARBATI'), ('FEMEI', 'FEMEI'), ('COPII', 'COPII')], default='FEMEI', verbose_name='Gen'),
        ),
    ]
