# Generated by Django 4.0 on 2022-02-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_alter_specificatii_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='reducere',
            field=models.FloatField(default=0, verbose_name='Reducere'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Nr de feedback-uri'),
        ),
    ]
