# Generated by Django 4.0 on 2022-02-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0007_specificatii_material_specificatii_sedecoloreaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificatii',
            name='gen',
            field=models.TextField(choices=[('Barbati', 'Barbati'), ('Femei', 'Femei'), ('Copii', 'Copii')], default='Femei', verbose_name='Gen'),
        ),
    ]
