# Generated by Django 4.0 on 2022-02-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_alter_specificatii_gen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pret',
            old_name='pret',
            new_name='pretul',
        ),
    ]
