# Generated by Django 4.0 on 2022-02-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsettings',
            name='hidelogin',
            field=models.BooleanField(default=False, verbose_name='Ascunde Loginul'),
        ),
        migrations.AlterField(
            model_name='ownsettings',
            name='productimagepath',
            field=models.CharField(default='Products/', max_length=20, verbose_name='Folderul unde se incarca imaginile produselor'),
        ),
        migrations.AlterField(
            model_name='ownsettings',
            name='showprice',
            field=models.BooleanField(default=True, verbose_name='Arata pretul'),
        ),
        migrations.AlterField(
            model_name='slideshowsettings',
            name='breakpoint',
            field=models.IntegerField(default=1000, verbose_name='Slideshowul opreste animatia la ecrane mai mici de(px)'),
        ),
        migrations.AlterField(
            model_name='slideshowsettings',
            name='imgpath',
            field=models.CharField(default='SlideShow/', max_length=50, verbose_name='Folderul imaginilor din slideshow'),
        ),
    ]
