# Generated by Django 4.0 on 2022-02-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_navbarsettings_hidelogin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownsettings',
            name='card',
        ),
        migrations.RemoveField(
            model_name='ownsettings',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='ownsettings',
            name='galerie',
        ),
        migrations.RemoveField(
            model_name='ownsettings',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='ownsettings',
            name='slideshow',
        ),
    ]
