# Generated by Django 4.0 on 2022-02-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_ownsettings_card_remove_ownsettings_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsettings',
            name='specificatii',
            field=models.CharField(default='marime rating', max_length=30, verbose_name='Specificatiile afisate'),
        ),
    ]
